In [36]:
import pandas as pd

In [37]:
## read data
data = pd.read_csv('QADSMLP-learner/data/renfe_trains.csv')

In [38]:
## data in dataframe to visualise properly
df = pd.DataFrame(data)

In [39]:
print(df)

      company  origin destination            departure              arrival  \
0       renfe  MADRID     SEVILLA  2019-05-07 19:00:00  2019-05-07 21:38:00
1       renfe  MADRID     SEVILLA  2019-05-07 21:25:00  2019-05-08 00:10:00
2       renfe  MADRID   BARCELONA  2019-05-11 08:30:00  2019-05-11 11:15:00
3       renfe  MADRID   BARCELONA  2019-04-18 14:30:00  2019-04-18 17:21:00
4       renfe  MADRID   BARCELONA  2019-04-28 16:30:00  2019-04-28 19:15:00
...       ...     ...         ...                  ...                  ...
85943   renfe  MADRID   BARCELONA  2020-10-20 08:00:00  2020-10-20 10:30:00
85944   renfe  MADRID   BARCELONA  2020-10-27 09:30:00  2020-10-27 12:34:12
85945   renfe  MADRID   BARCELONA  2020-10-23 07:30:00  2020-10-23 10:40:12
85946   renfe  MADRID   BARCELONA  2020-10-08 07:40:00  2020-10-08 13:55:00
85947   renfe  MADRID   BARCELONA  2020-11-08 16:30:00  2020-11-08 19:15:00

            vehicle_class  price      fare
0              Preferente   69.4     Promo
1                 Turista  43.55     Promo
2                 Turista   85.1     Promo
3                 Turista  107.7  Flexible
4                 Turista  107.7  Flexible
...                   ...    ...       ...
85943             Turista  55.25   Promo +
85944             Turista  55.55   Promo +
85945             Turista  46.85   Promo +
85946  Turista con enlace   96.7  Flexible
85947             Turista  108.9  Flexible

[85948 rows x 8 columns]

In [40]:
## inspect columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 85948 entries, 0 to 85947
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   company        85948 non-null  object
 1   origin         85948 non-null  object
 2   destination    85948 non-null  object
 3   departure      85948 non-null  object
 4   arrival        85948 non-null  object
 5   vehicle_class  77116 non-null  object
 6   price          72769 non-null  object
 7   fare           77116 non-null  object
dtypes: object(8)
memory usage: 5.2+ MB

In [41]:
## there are some values in price column with value "price". .value_counts() is used to visualise them
df['price'].value_counts()

price
price    3875
76.3     3794
85.1     3615
107.7    2845
53.4     2719
         ...
98.01       1
98.2        1
69.05       1
19.75       1
61.15       1
Name: count, Length: 389, dtype: int64

In [42]:
## inspecting the rows that have the value price via masking
## df['price'] == 'price' creates a boolean series for each row (true or false)
## df[boolean_series] keeps rows where boolean is true and drops rows where the boolean is false
df[df['price'] == 'price']

,company,origin,destination,departure,arrival,vehicle_class,price,fare
69,company,origin,destination,departure,arrival,vehicle_class,price,fare
146,company,origin,destination,departure,arrival,vehicle_class,price,fare
209,company,origin,destination,departure,arrival,vehicle_class,price,fare
287,company,origin,destination,departure,arrival,vehicle_class,price,fare
347,company,origin,destination,departure,arrival,vehicle_class,price,fare
...,...,...,...,...,...,...,...,...
85903,company,origin,destination,departure,arrival,vehicle_class,price,fare
85908,company,origin,destination,departure,arrival,vehicle_class,price,fare
85921,company,origin,destination,departure,arrival,vehicle_class,price,fare
85934,company,origin,destination,departure,arrival,vehicle_class,price,fare
85942,company,origin,destination,departure,arrival,vehicle_class,price,fare

In [43]:
## drop rows
df = df[df['price'] != 'price']

In [44]:
import numpy as np

In [45]:
## converting price to appropriate type
## astype() is a pandas method (not numpy), but it uses numpy data types like np.float32
df['price'] = df['price'].astype(np.float32)

In [46]:
# mv = df.isnull
mv = df.isna().any

In [47]:
mv

<bound method DataFrame.any of        company  origin  destination  departure  arrival  vehicle_class  price  \
0        False   False        False      False    False          False  False
1        False   False        False      False    False          False  False
2        False   False        False      False    False          False  False
3        False   False        False      False    False          False  False
4        False   False        False      False    False          False  False
...        ...     ...          ...        ...      ...            ...    ...
85943    False   False        False      False    False          False  False
85944    False   False        False      False    False          False  False
85945    False   False        False      False    False          False  False
85946    False   False        False      False    False          False  False
85947    False   False        False      False    False          False  False

        fare
0      False
1      False
2      False
3      False
4      False
...      ...
85943  False
85944  False
85945  False
85946  False
85947  False

[82073 rows x 8 columns]>

In [48]:
## finding null values in vehicle class, price and fare
df.isna().sum()

company              0
origin               0
destination          0
departure            0
arrival              0
vehicle_class     8832
price            13179
fare              8832
dtype: int64

In [49]:
df[df['price'].isna()]

,company,origin,destination,departure,arrival,vehicle_class,price,fare
11,renfe,MADRID,BARCELONA,2019-05-03 18:30:00,2019-05-03 21:20:00,Preferente,NaN,Promo
15,renfe,MADRID,BARCELONA,2019-04-23 07:30:00,2019-04-23 10:40:00,Turista,NaN,Promo
33,renfe,MADRID,SEVILLA,2019-04-21 21:25:00,2019-04-22 00:10:00,NaN,NaN,NaN
52,renfe,MADRID,SEVILLA,2019-04-17 09:45:00,2019-04-17 12:27:00,Turista,NaN,Flexible
65,renfe,MADRID,SEVILLA,2019-05-03 13:30:00,2019-05-03 16:05:00,Turista,NaN,Promo
...,...,...,...,...,...,...,...,...
85847,renfe,MADRID,SEVILLA,2020-11-22 09:00:00,2020-11-22 11:37:48,NaN,NaN,NaN
85850,renfe,MADRID,SEVILLA,2020-10-13 11:22:00,2020-10-13 16:05:12,NaN,NaN,NaN
85854,renfe,MADRID,BARCELONA,2020-11-06 10:30:00,2020-11-06 13:15:00,NaN,NaN,NaN
85866,renfe,MADRID,SEVILLA,2020-12-04 12:00:00,2020-12-04 14:31:48,NaN,NaN,NaN
85871,renfe,MADRID,SEVILLA,2020-10-13 11:22:00,2020-10-13 16:05:12,NaN,NaN,NaN

In [50]:
## drop all rows which have missing vehicle_class, price and fare
df.dropna(subset = ['vehicle_class', 'price', 'fare'], how='all', inplace=True)

In [51]:
df[['vehicle_class', 'fare', 'price']].groupby(['vehicle_class', 'fare']).mean()

                                                       price
vehicle_class            fare
Cama G. Clase            Doble Familiar-Flexible   98.199997
                         Individual-Flexible      150.600006
Cama Turista             Flexible                  74.224998
Preferente               Flexible                 118.568962
                         Mesa                     342.799988
                         Promo                     76.151573
                         Promo +                   91.770325
PreferenteSólo plaza H   Flexible                  87.400002
                         Promo                     60.819565
Turista                  Adulto ida                44.249088
                         Básica                    46.240158
                         COD.PROMOCIONAL           68.483330
                         Flexible                  85.300377
                         Mesa                     172.399994
                         Promo                     64.925781
                         Promo +                   72.272072
                         YOVOY                     53.171658
Turista Plus             Flexible                 124.547058
                         Mesa                     206.800003
                         Promo                     86.225685
                         Promo +                   81.960510
                         YOVOY                     61.976925
Turista PlusSólo plaza H Flexible                  80.599998
Turista con enlace       Flexible                  62.770576
                         Promo                     45.170784
                         Promo +                   40.896313
                         YOVOY                     33.099998
TuristaSólo plaza H      Flexible                  95.176750
                         Promo                     80.128578

In [52]:
## fill the remaining price values with mean of all prices
df.fillna({'price': df['price'].mean()}, inplace=True)

In [53]:
## Deduplication
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
85943    False
85944    False
85945     True
85946    False
85947     True
Length: 73241, dtype: bool

In [54]:
## drop duplicates. Use inplace=True to drop them inplace
df.drop_duplicates(inplace=True)

In [55]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
85940    False
85941    False
85943    False
85944    False
85946    False
Length: 29724, dtype: bool

In [56]:
## outliers
q1= np.percentile(df['price'], 25)

In [57]:
q3 = np.percentile(df['price'], 75)

In [58]:
iqr = q3 - q1

In [59]:
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 - 1.5 * iqr

In [60]:
outliers = [x for x in df['price'] if x < lower_bound or x > upper_bound]

In [61]:
print(outliers)

[69.4000015258789, 43.54999923706055, 85.0999984741211, 107.69999694824219, 107.69999694824219, 78.80000305175781, 75.4000015258789, 85.0999984741211, 58.150001525878906, 76.30000305175781, 85.0999984741211, 71.49380493164062, 43.25, 85.0999984741211, 60.29999923706055, 71.49380493164062, 85.0999984741211, 106.75, 69.80000305175781, 58.150001525878906, 60.29999923706055, 38.54999923706055, 90.5, 69.4000015258789, 69.4000015258789, 76.30000305175781, 69.4000015258789, 90.5, 43.54999923706055, 62.20000076293945, 94.55000305175781, 66.75, 53.400001525878906, 69.4000015258789, 76.30000305175781, 76.30000305175781, 80.1500015258789, 49.54999923706055, 78.80000305175781, 58.150001525878906, 85.0999984741211, 60.29999923706055, 47.29999923706055, 76.30000305175781, 75.4000015258789, 85.0999984741211, 60.29999923706055, 90.5, 78.80000305175781, 69.4000015258789, 71.49380493164062, 47.29999923706055, 53.400001525878906, 57.95000076293945, 68.6500015258789, 43.54999923706055, 75.4000015258789, 53.400001525878906, 78.80000305175781, 76.30000305175781, 78.80000305175781, 53.400001525878906, 58.95000076293945, 71.49380493164062, 71.49380493164062, 52.20000076293945, 76.30000305175781, 88.94999694824219, 47.29999923706055, 76.30000305175781, 43.54999923706055, 47.29999923706055, 76.30000305175781, 76.30000305175781, 76.30000305175781, 58.150001525878906, 85.0999984741211, 66.75, 71.49380493164062, 47.29999923706055, 80.1500015258789, 49.150001525878906, 71.49380493164062, 58.150001525878906, 75.4000015258789, 85.0999984741211, 85.0999984741211, 53.400001525878906, 71.49380493164062, 85.0999984741211, 68.6500015258789, 85.0999984741211, 62.20000076293945, 58.150001525878906, 102.1500015258789, 43.54999923706055, 71.49380493164062, 75.4000015258789, 80.1500015258789, 71.49380493164062, 76.30000305175781, 102.1500015258789, 64.05000305175781, 78.80000305175781, 71.49380493164062, 127.0999984741211, 75.4000015258789, 40.95000076293945, 82.3499984741211, 85.0999984741211, 69.80000305175781, 53.400001525878906, 102.1500015258789, 71.49380493164062, 60.29999923706055, 107.69999694824219, 58.95000076293945, 90.5, 71.49380493164062, 80.1500015258789, 71.49380493164062, 66.75, 75.4000015258789, 49.54999923706055, 76.30000305175781, 62.20000076293945, 85.0999984741211, 81.4000015258789, 66.75, 80.1500015258789, 43.25, 69.80000305175781, 43.25, 76.30000305175781, 76.30000305175781, 107.69999694824219, 82.3499984741211, 64.05000305175781, 75.4000015258789, 76.30000305175781, 107.69999694824219, 94.55000305175781, 49.150001525878906, 100.4000015258789, 62.20000076293945, 75.4000015258789, 106.75, 75.4000015258789, 107.69999694824219, 115.6500015258789, 60.29999923706055, 76.30000305175781, 87.4000015258789, 102.1500015258789, 47.29999923706055, 71.49380493164062, 71.49380493164062, 107.69999694824219, 94.55000305175781, 78.80000305175781, 75.4000015258789, 107.69999694824219, 80.1500015258789, 66.75, 52.20000076293945, 49.150001525878906, 47.29999923706055, 85.0999984741211, 43.54999923706055, 47.29999923706055, 58.150001525878906, 47.29999923706055, 76.30000305175781, 102.1500015258789, 76.30000305175781, 90.5, 85.0999984741211, 58.150001525878906, 58.150001525878906, 40.95000076293945, 88.94999694824219, 76.30000305175781, 90.5, 43.25, 71.49380493164062, 107.69999694824219, 100.4000015258789, 62.20000076293945, 85.08000183105469, 88.94999694824219, 60.29999923706055, 75.4000015258789, 71.49380493164062, 47.29999923706055, 71.49380493164062, 107.69999694824219, 76.30000305175781, 71.49380493164062, 64.05000305175781, 43.54999923706055, 47.29999923706055, 107.69999694824219, 67.19999694824219, 53.400001525878906, 47.29999923706055, 76.30000305175781, 100.4000015258789, 76.30000305175781, 94.55000305175781, 75.4000015258789, 107.69999694824219, 76.30000305175781, 43.25, 71.49380493164062, 85.0999984741211, 87.4000015258789, 181.5, 85.0999984741211, 69.80000305175781, 76.30000305175781, 85.0999984741211, 62.20000076293945, 112.55000305175781, 53.400001525878906, 71.49380493164062, 76.30000305175781, 71.49380493164062, 78.80000305175781, 78.30000305175781, 53.400001525878906, 75.4000015258789, 47.29999923706055, 102.1500015258789, 64.05000305175781, 66.75, 107.69999694824219, 66.75, 76.30000305175781, 100.4000015258789, 60.29999923706055, 75.4000015258789, 53.400001525878906, 102.1500015258789, 76.30000305175781, 71.49380493164062, 69.4000015258789, 58.45000076293945, 107.69999694824219, 102.1500015258789, 71.49380493164062, 71.49380493164062, 71.49380493164062, 94.55000305175781, 58.95000076293945, 75.4000015258789, 85.0999984741211, 71.49380493164062, 78.80000305175781, 127.0999984741211, 69.4000015258789, 60.29999923706055, 45.79999923706055, 76.30000305175781, 82.3499984741211, 66.75, 71.49380493164062, 69.4000015258789, 71.49380493164062, 53.400001525878906, 43.54999923706055, 60.29999923706055, 66.75, 107.69999694824219, 43.25, 75.4000015258789, 69.4000015258789, 85.0999984741211, 102.1500015258789, 58.150001525878906, 75.4000015258789, 100.4000015258789, 38.54999923706055, 61.45000076293945, 69.4000015258789, 49.150001525878906, 60.29999923706055, 69.4000015258789, 71.49380493164062, 60.29999923706055, 127.0999984741211, 76.30000305175781, 75.4000015258789, 85.0999984741211, 107.69999694824219, 71.49380493164062, 107.69999694824219, 52.45000076293945, 127.0999984741211, 85.0999984741211, 69.4000015258789, 62.20000076293945, 60.29999923706055, 47.29999923706055, 71.49380493164062, 75.4000015258789, 76.30000305175781, 75.4000015258789, 102.1500015258789, 75.4000015258789, 90.5, 90.5, 107.69999694824219, 75.4000015258789, 66.75, 76.30000305175781, 71.49380493164062, 91.5, 58.150001525878906, 87.4000015258789, 58.150001525878906, 102.1500015258789, 127.0999984741211, 60.29999923706055, 85.0999984741211, 53.400001525878906, 47.29999923706055, 69.4000015258789, 53.400001525878906, 66.75, 53.400001525878906, 100.4000015258789, 85.0999984741211, 76.30000305175781, 53.400001525878906, 107.69999694824219, 88.94999694824219, 69.4000015258789, 47.29999923706055, 85.0999984741211, 94.55000305175781, 69.4000015258789, 71.49380493164062, 76.30000305175781, 71.49380493164062, 88.94999694824219, 71.49380493164062, 127.0999984741211, 68.6500015258789, 71.49380493164062, 76.30000305175781, 43.54999923706055, 78.80000305175781, 47.29999923706055, 69.80000305175781, 59.5, 49.54999923706055, 75.4000015258789, 64.05000305175781, 49.54999923706055, 90.5, 90.5, 76.30000305175781, 66.75, 107.69999694824219, 43.54999923706055, 49.150001525878906, 60.29999923706055, 59.5, 66.75, 82.3499984741211, 128.5, 58.150001525878906, 75.4000015258789, 100.4000015258789, 71.49380493164062, 71.49380493164062, 71.49380493164062, 76.30000305175781, 69.4000015258789, 61.45000076293945, 71.49380493164062, 60.29999923706055, 68.6500015258789, 82.3499984741211, 61.45000076293945, 53.400001525878906, 71.49380493164062, 49.150001525878906, 71.49380493164062, 47.29999923706055, 80.1500015258789, 76.30000305175781, 78.80000305175781, 52.45000076293945, 76.30000305175781, 76.30000305175781, 85.0999984741211, 85.0999984741211, 127.0999984741211, 69.4000015258789, 90.5, 71.49380493164062, 71.49380493164062, 43.25, 88.94999694824219, 60.29999923706055, 53.400001525878906, 75.4000015258789, 66.75, 78.80000305175781, 71.49380493164062, 52.45000076293945, 71.49380493164062, 60.29999923706055, 58.150001525878906, 49.54999923706055, 60.29999923706055, 100.4000015258789, 47.29999923706055, 69.80000305175781, 102.1500015258789, 107.69999694824219, 49.150001525878906, 38.54999923706055, 88.94999694824219, 100.4000015258789, 61.45000076293945, 85.0999984741211, 76.30000305175781, 43.54999923706055, 107.69999694824219, 60.29999923706055, 71.49380493164062, 53.400001525878906, 54.45000076293945, 62.20000076293945, 69.4000015258789, 67.19999694824219, 71.49380493164062, 78.80000305175781, 76.30000305175781, 47.29999923706055, 85.0999984741211, 76.30000305175781, 75.4000015258789, 40.95000076293945, 85.0999984741211, 88.94999694824219, 71.49380493164062, 90.5, 107.69999694824219, 76.30000305175781, 102.1500015258789, 107.69999694824219, 76.30000305175781, 71.49380493164062, 62.20000076293945, 53.400001525878906, 71.49380493164062, 76.30000305175781, 60.29999923706055, 88.94999694824219, 76.30000305175781, 43.25, 76.30000305175781, 62.20000076293945, 85.0999984741211, 47.29999923706055, 53.400001525878906, 62.20000076293945, 43.25, 90.5, 49.54999923706055, 45.79999923706055, 107.69999694824219, 49.54999923706055, 85.0999984741211, 76.30000305175781, 75.4000015258789, 107.69999694824219, 76.30000305175781, 60.29999923706055, 58.150001525878906, 85.0999984741211, 76.30000305175781, 71.49380493164062, 85.0999984741211, 90.5, 85.0999984741211, 107.69999694824219, 49.150001525878906, 85.0999984741211, 107.69999694824219, 81.4000015258789, 60.29999923706055, 58.95000076293945, 71.49380493164062, 75.4000015258789, 107.69999694824219, 107.69999694824219, 43.54999923706055, 53.400001525878906, 76.30000305175781, 76.30000305175781, 71.49380493164062, 85.0999984741211, 71.49380493164062, 61.45000076293945, 80.1500015258789, 99.0999984741211, 71.49380493164062, 115.6500015258789, 76.30000305175781, 75.4000015258789, 43.25, 76.30000305175781, 85.0999984741211, 100.4000015258789, 76.30000305175781, 53.400001525878906, 76.30000305175781, 61.45000076293945, 71.49380493164062, 53.400001525878906, 49.54999923706055, 71.49380493164062, 66.75, 76.30000305175781, 90.5, 76.30000305175781, 69.4000015258789, 53.400001525878906, 87.4000015258789, 49.54999923706055, 85.0999984741211, 49.150001525878906, 75.4000015258789, 102.1500015258789, 64.05000305175781, 85.0999984741211, 60.29999923706055, 58.150001525878906, 102.1500015258789, 90.5, 66.75, 90.5, 49.54999923706055, 75.4000015258789, 49.54999923706055, 85.0999984741211, 76.30000305175781, 71.49380493164062, 85.0999984741211, 60.29999923706055, 85.0999984741211, 71.49380493164062, 85.0999984741211, 106.75, 76.30000305175781, 71.49380493164062, 53.400001525878906, 60.29999923706055, 62.20000076293945, 94.55000305175781, 102.1500015258789, 71.49380493164062, 69.4000015258789, 69.4000015258789, 68.6500015258789, 69.4000015258789, 69.4000015258789, 88.94999694824219, 60.29999923706055, 107.69999694824219, 90.5, 60.29999923706055, 76.30000305175781, 85.0999984741211, 107.69999694824219, 85.0999984741211, 71.49380493164062, 62.20000076293945, 78.80000305175781, 76.30000305175781, 47.29999923706055, 62.20000076293945, 71.49380493164062, 69.80000305175781, 76.30000305175781, 60.29999923706055, 60.29999923706055, 76.30000305175781, 49.150001525878906, 102.1500015258789, 69.4000015258789, 61.45000076293945, 90.5, 49.150001525878906, 75.4000015258789, 75.4000015258789, 85.0999984741211, 69.4000015258789, 66.75, 49.150001525878906, 47.29999923706055, 107.69999694824219, 72.30000305175781, 75.4000015258789, 69.4000015258789, 53.400001525878906, 76.30000305175781, 49.54999923706055, 43.25, 107.69999694824219, 47.29999923706055, 88.94999694824219, 115.6500015258789, 58.150001525878906, 49.54999923706055, 75.4000015258789, 69.4000015258789, 60.29999923706055, 127.0999984741211, 49.54999923706055, 90.5, 76.30000305175781, 71.49380493164062, 60.29999923706055, 76.30000305175781, 53.400001525878906, 76.30000305175781, 107.69999694824219, 43.54999923706055, 62.20000076293945, 71.49380493164062, 85.0999984741211, 60.29999923706055, 43.25, 71.49380493164062, 53.400001525878906, 60.29999923706055, 47.29999923706055, 80.1500015258789, 127.0999984741211, 76.30000305175781, 75.4000015258789, 61.20000076293945, 107.69999694824219, 80.1500015258789, 88.94999694824219, 68.94999694824219, 100.4000015258789, 107.69999694824219, 85.0999984741211, 62.20000076293945, 53.400001525878906, 71.49380493164062, 127.0999984741211, 127.0999984741211, 71.49380493164062, 71.49380493164062, 71.49380493164062, 75.4000015258789, 88.94999694824219, 71.49380493164062, 76.30000305175781, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 76.30000305175781, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 53.400001525878906, 71.49380493164062, 71.49380493164062, 71.49380493164062, 69.4000015258789, 71.49380493164062, 69.4000015258789, 71.49380493164062, 71.49380493164062, 62.20000076293945, 76.30000305175781, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 47.29999923706055, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 62.20000076293945, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 128.5, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.49380493164062, 71.493804931640

In [62]:
## split the dataset into training and testing sets assuming you are trying to predict price
from sklearn.model_selection import train_test_split

In [63]:
features = list(set(df.columns) - {'price'})

In [64]:
target = ['price']

In [65]:
X_train, X_test, y_train, y_test = train_test_split(df[features], df[target], test_size=0.2)

In [66]:
## standardising using StandardScaler
from sklearn.preprocessing import StandardScaler

In [67]:
object = StandardScaler()

In [68]:
y_train = object.fit_transform(y_train)
y_test = object.fit_transform(y_test)

In [69]:
## encode destination column
from sklearn.preprocessing import OneHotEncoder

destination_encoder = OneHotEncoder(sparse_output=False)
X_train[destination_encoder.get_feature_names_out()] = destination_encoder.fit_transform(X_train[['destination']])
X_train.drop('destination', axis=1, inplace=True)
X_train

,origin,vehicle_class,arrival,company,fare,departure,destination_BARCELONA,destination_PONFERRADA,destination_SEVILLA
4528,MADRID,Turista,2019-04-20 11:15:00,renfe,Promo,2019-04-20 08:30:00,1.0,0.0,0.0
83669,MADRID,Turista,2020-08-28 09:34:00,renfe,YOVOY,2020-08-28 06:20:00,1.0,0.0,0.0
55261,MADRID,Turista,2019-12-06 23:55:00,renfe,Promo,2019-12-06 21:25:00,1.0,0.0,0.0
4138,MADRID,Turista,2019-05-04 11:15:00,renfe,Promo,2019-05-04 08:30:00,1.0,0.0,0.0
68478,MADRID,Turista,2020-05-10 13:32:00,renfe,Promo,2020-05-10 11:00:00,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...
82834,MADRID,Turista,2020-09-13 20:40:00,renfe,Flexible,2020-09-13 17:30:00,1.0,0.0,0.0
84945,MADRID,Turista,2020-10-24 11:37:48,renfe,Promo +,2020-10-24 09:00:00,0.0,0.0,1.0
44164,MADRID,Turista Plus,2019-08-12 12:34:00,renfe,Promo,2019-08-12 09:30:00,1.0,0.0,0.0
43813,MADRID,Turista,2019-08-15 10:40:00,renfe,Promo,2019-08-15 07:30:00,1.0,0.0,0.0
68022,MADRID,Preferente,2020-03-08 19:15:00,renfe,Flexible,2020-03-08 16:30:00,1.0,0.0,0.0